app/DjangoUeditor/urls.py
#!/usr/bin/env python
# coding: utf-8

from django.conf.urls import patterns, url
from DjangoUeditor.views import UploadFile,ImageManager,RemoteCatchImage,SearchMovie,scrawlUp

urlpatterns = patterns('',
    url(r'^ImageUp/(?P<uploadpath>.*)', UploadFile, {'uploadtype':'image'}),
    url(r'^FileUp/(?P<uploadpath>.*)', UploadFile, {'uploadtype':'file'}),
    url(r'^scrawlUp/(?P<uploadpath>.*)$', scrawlUp),
    url(r'^ImageManager/(?P<imagepath>.*)$', ImageManager),
    url(r'^RemoteCatchImage/(?P<imagepath>.*)$', RemoteCatchImage),
    url(r'^SearchMovie/$', SearchMovie),
)
 

app/bbs/urls.py
from django.conf.urls import patterns, include, url
import os
from bbs import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bbs.views.home', name='home'),
    # url(r'^bbs/', include('bbs.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include(admin.site.urls)),
)


urlpatterns += patterns('',
    
    url(r'^$', 'forum.views.index'),
    url(r'^bbs/', include('forum.urls')),
    url(r'^ueditor/', include('DjangoUeditor.urls')),

)


urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

)


urlpatterns += patterns('',

    url(r'^css/(?P<path>.*)','django.views.static.serve',{'document_root':os.path.join(os.path.dirname(__file__), './templates/css').replace('\\', '/')}),
    url(r'^js/(?P<path>.*)','django.views.static.serve',{'document_root':os.path.join(os.path.dirname(__file__), './templates/js').replace('\\', '/')}),
    url(r'^images/(?P<path>.*)','django.views.static.serve',{'document_root':os.path.join(os.path.dirname(__file__), './templates/images').replace('\\', '/')}),

        
)

app/forum/forms.py
# coding: utf-8

from django import forms
from DjangoUeditor.forms import UEditorField


class UserForm(forms.Form):
    
    username = forms.CharField(label=u'用户名', max_length=30)
    email = forms.EmailField(label=u'邮箱')
    password1 = forms.CharField(label=u'密码', widget=forms.PasswordInput())
    password2 = forms.CharField(label=u'确认密码', widget=forms.PasswordInput())
    
class ChangePwd(forms.Form):
    
    email = forms.EmailField(label=u'邮箱')
    oldpassword = forms.CharField(label=u'旧密码', widget=forms.PasswordInput())
    password1 = forms.CharField(label=u'新密码', widget=forms.PasswordInput())
    password2 = forms.CharField(label=u'确认密码', widget=forms.PasswordInput())
    
class PostsForm(forms.Form):
    title = forms.CharField(label=u'标题', max_length=30)
    details = UEditorField(label=u'内容')

class SubpostForm(forms.Form):
    comments = UEditorField(label=u'回复')

templates/base.html
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title> {% block title %}{% endblock %}</title>
	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.css">	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">	
	
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>  

<body>


{% block content %}{% endblock %}
{% block footer %}
{% endblock %}

</body>
</html>

templates/changepwd.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>更改密码</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.css">	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">	
	
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>  

</head>
<body>
<div class='span12'>
    <p align='center'><b>my bbs</b></p><hr />
</div>


<div class="span12">
    <div class="span12">
        <span class="label label-info">{{ request.session.username }}</span>&nbsp;&nbsp;正在更改密码...
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span ><a href='/'>返回首页</a></span>
        <hr class="span11"  />
    </div>    
    <div class=" form-horizontal">
        <form action='/bbs/changepwd/' method='POST'>
            
            <div class="control-group">    
                <label class="control-label" for="id_email">邮箱：</label>    
                        {{ form.email }}
            </div>
            <div class="control-group">    
                <label class="control-label" for="id_oldpassword">原密码：</label>   
                        {{ form.oldpassword }}
            </div>           
            <div class="control-group">    
                <label class="control-label" for="id_password1">密码：</label>
                        {{ form.password1 }}
            </div>
            
            <div class="control-group">    
                <label class="control-label" for="id_password2">确认密码：</label>       
                        {{ form.password2 }}
            </div>
            <div class="span10 form-actions">
        	   <input class="btn btn-success" type="submit" value="提交">
        	   <a href="/"><input class="btn btn-warning" type="button" value="取消"></a>      
            </div>
        </form>
    </div>
</div>
</body>
</html>

templates/content.html
{% extends 'base.html' %}

{% block title %}首页{% endblock %}<br />

<hr />
{% block content %}

<div class='span12'>
    <p align='center'><b>my bbs</b></p><hr />
</div>


<div class="span12">

    {% if request.session.username %}
    <div class="span3">
        <a href="/bbs/postsadd/" > <input class='btn btn-primary' type="button" value='发帖' /></a>
        &nbsp;
        <span>欢迎</span>{{request.session.username}}<span>回来</span>
            &nbsp;   
        <a href="/bbs/logout/" >登出</a>&nbsp;&nbsp;<a href='/bbs/changepwd/'>更改密码</a><br />
        <br />
        <a href='/bbs/postsmanage/'>管理自己的帖子</a>
    {% else %}
    </div>

    <div class="span12">
        <div class="span3">
            <h3>H3IDAN</h3>
        </div>        
        
        <form class=" form-horizontal" action="/bbs/login/" method="POST" style="float:right">
            <input type="text" name="email" placeholder="邮件" />
            <input type="password" name="passwd" placeholder="密码" />
            {# <a href='/bbs/retrievepwd/'>忘记密码？</a> #}
            <input class='btn-info' type="submit" value="登录">
            <a href="/bbs/register/" ><input class='btn-info' type="button" value="注册"></a>
        </form>
        
    </div>
        {% endif %}
</div>

<hr class="span12" />

<div class="span12">

    <span class="span1 label label-info">帖子列表</span>
    <hr class="span11" />
    <div class="span12">
    {% if info %}
    	{% for post in posts_list.object_list %}
    		
    		<div class='span5'>
    		    <div>
        		    <span class="label label-success">标题</span>
        		    <a href='/bbs/replys/{{ post.id }}'>{{ post.title }}</a><br />
                </div>
                <div>
                    <span class="label label-success">作者</span>
                    {{ post.user.username }}
                </div>            
                <div>
                    <span class="label label-success">帖子内容</span>
                    <div class="post_details">      		        
      		        {{ post.details|safe }}
      		        </div>
                </div>
            </div>
            <hr class="span10" />
    	{% endfor %}
    {% else %}
    </div>
        <div class="span12">	
    	   <p>还没有人发帖哦！！</p>
    	</div>
    {% endif %}
    </div>

    <hr class="span11" />

    <div class='span2' >
        {% if has_previous %}
        	<a href="/?page={{ previous }}">上一页</a>
        {% endif %}
        
        {% if has_next %}
        	<a href="/?page={{ next }}"></a>
        {% endif %}
        
        {% if posts_list.has_previous %}
        	<a href="?page={{ posts_list.previous_page_number }}" title="下一页">上一页</a>&nbsp;
        {% endif %}
        
        {% for p in page_range %}
        	{% ifequal p posts_list.number %}
        		<span>第{{ p }}页   </span>
        	{% else %}
        		<a href="?page={{ p }}" title="第{{ p }}页">{{ p }}</a>
        	{% endifequal %}
        {% endfor %}
        
        &nbsp;
        
        {% if posts_list.has_next %}
        	<a href="?page={{ posts_list.next_page_number }}" title="下一页">下一页</a>&nbsp;
        {% endif %}
    </div>
</div>
{% endblock %}

templates/fail_login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>登录失败</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.css">	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">	
	
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>  
</head>
<body>

<div class='span12'>
    <p align='center'><b>my bbs</b></p><hr />
</div>

<div class="span12">
    
    <div class="span11">
    <span class="label label-success">登录失败</span>
    </div> 
    <hr class="span11"/>  
    <span class='span10'>   
    您输入的邮箱或密码不正确，请您<a href='/'>返回</a>重新输入</span>
    </span>

</div>


</body>
</html>

templates/fail_reg.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>注册失败</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.css">	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">	
	
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>  
</head>
<body>

<div class='span12'>
    <p align='center'><b>my bbs</b></p><hr />
</div>

<div class="span12">
    
    <div class="span11">
    <span class="label label-success">注册失败</span>
    </div> 
    <hr class="span11"/>  
    <span class='span10'>   
    您输入的两次密码不相同，请您<a href='/bbs/register/'>返回</a>重新注册</span>
    </span>

</div>


</body>
</html>

templates/fail_rep.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>回复失败</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.css">	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">	
	
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>  
</head>
<body>

<div class='span12'>
    <p align='center'><b>my bbs</b></p><hr />
</div>

<div class="span12">
    
    <div class="span11">
    <span class="label label-success">回复失败</span>
    </div> 
    <hr class="span11"/>  
    <span class='span10'>   
    您没有登录，不能回复该帖子。请您<a href='/'>返回首页</a>登录。</span>
    </span>

</div>


</body>
</html>

templates/posts.html
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title></title>
</head>
<body>

<form action="/bbs/postsadd/" method="POST">
    
    {{ form.as_table }}
    <p>作者：{{ request.session.username }}</p>
	<br />

	<input type="submit" value="提交" />
	
</form>

</body>
</html>

templates/postsadd.html
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
{#	<meta http-equiv="refresh" content="0; url=http://localhost:8000/" />  #}
	<title>发帖</title>
	{{ form.media }}
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.css">	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">	
	
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>  
<body>

<div class='span12'>
    <p align='center'><b>my bbs</b></p><hr />
</div>

<div class="span12">
    <span class="span1 label label-info ">发表帖子</span>
    &nbsp;
    <span ><a href='/'>返回首页</a></span>
</div>
<div class="span12"><hr /></div>
<div class="span12" >
    <form action="/bbs/posts/" method="POST">
        
        <div class="">
            <label for="id_title">标题：{{ form.title }}</label>
        </div>
        <div class="">
            <label for="id_username">作者：{{ request.session.username }}</label>
        </div>
        <div class="">    
            <label for="id_details">内容：</label>
            {{ form.details }}
        </div>
    	<br />
    
    	<input class="btn btn-success" type="submit" value="提交" />
    	<a href="/"><input class="btn btn-warning" type="button" value="取消" /></a>


    </form>
</div>

</body>
</html>

templates/postsmanage.html
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>帖子管理</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.css">	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">	
	
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>  

</head>
<body>
<div class='span12'>
    <p align='center'><b>my bbs</b></p><hr />
</div>

<div class="span12">
    <span class="btn-info ">帖子管理</span>
<hr />
<span class="label label-info">用户</span>&nbsp;{{ request.session.username }}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="/"><button class="label label-info">回到首页</button></a>
<br />
<br />


{% if posts %}
	{% for post in posts_list.object_list %}
		{% if request.session.email == post.user.email  %}
		<pre>	
    		标题：<a href='/bbs/cnhei/{{ post.id }}'>{{ post.title }}</a>
    		作者：{{ post.user.username }}
    		内容：{{ post.details|safe}}
    		<br />
    		<a href='/bbs/postsdel/{{post.id}}'>删除</a>
        </pre>
    	{% endif %}	
	{% endfor %}
{% else %}
	<pre><span>这里已经没有帖子了！！！</span></pre>
	<hr />
{% endif %}


<div class='span2' >
    {% if has_previous %}
    	<a href="/?page={{ previous }}">上一页</a>
    {% endif %}
    
    {% if has_next %}
    	<a href="/?page={{ next }}"></a>
    {% endif %}
    
    {% if posts_list.has_previous %}
    	<a href="?page={{ posts_list.previous_page_number }}" title="下一页">上一页</a>&nbsp;
    {% endif %}
    
    {% for p in page_range %}
    	{% ifequal p posts_list.number %}
    		<span>第{{ p }}页   </span>
    	{% else %}
    		<a href="?page={{ p }}" title="第{{ p }}页">{{ p }}</a>
    	{% endifequal %}
    {% endfor %}
    
    &nbsp;
    
    {% if posts_list.has_next %}
    	<a href="?page={{ posts_list.next_page_number }}" title="下一页">下一页</a>&nbsp;
    {% endif %}
</div>

</body>
</html>

templates/registers.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>注册页面</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.css">	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">	
	
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
    
</head>

<body>

<div class='span12'>
    <p align='center'><b>my bbs</b></p><hr />
</div>


<div class="span12">
    <div class="span12">
        <span class="label label-info">请您注册：</span>&nbsp;&nbsp;
        <span ><a href='/'>返回首页</a></span>
        <hr class="span11"  />
    </div>  
    <div class=" form-horizontal">
        <form action='/bbs/register/' method='POST'>
            
            <div class="control-group">    
                <label class="control-label" for="id_username">用户名：</label>     
                        {{ form.username }}   
            </div>
            
            <div class="control-group">    
                <label class="control-label" for="id_email">邮箱：</label>         
                        {{ form.email }}
            </div>
            
            <div class="control-group">    
                <label class="control-label" for="id_password1">密码：</label>
                        {{ form.password1 }}
            </div>
            
            <div class="control-group">    
                <label class="control-label" for="id_password2">确认密码：</label>
                        {{ form.password2 }}
            </div>
            <div class="span10 form-actions">
        	   <input class="btn btn-success" type="submit" value="提交">
        	   <a href="/"><input class="btn btn-warning" type="button" value="取消"></a>
        	</div>
        </form>
    </div>
</div>


</body>
</html>

templates/subpost.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{{ nameid.title }}</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.css">	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">	
	
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script> 
    {{ form.media }}
</head>
<body>

<div class='span12'>
    <p align='center'><b>my bbs</b></p><hr />
</div>


<div class="span12">

    <span class="label label-info">帖子内容：</span>&nbsp;&nbsp;
    <span ><a href='/'>返回首页</a></span>
    <hr class="span11"  />

    <div class="span11">
   		<div class='span5'>    
            <div class="span10">            
                <span class="label label-success">标题</span>&nbsp;
                {{ nameid.title }}
            </div>
            <div class="span10">            
                <span class="label label-success">作者</span>&nbsp;
                {{ nameid.user.username }}<br />
            </div>
            <div class="span10">            
                <span class="label label-success">内容</span>&nbsp;
                {{ nameid.details|safe }}
            </div>
    	</div>
        <hr class="span11" />
        <div class="span11">
            <div class="span1 label label-info">回复内容：</div>
            <hr class="span10" />
            
            {% if replys %}
            	{% for post in posts_list.object_list %}	
            <div class="span10">            
                <span class="label label-success">作者</span>&nbsp;
                {{ post.user.username }}
            </div>            		
            
            <div class="span10">            
                <span class="label label-success">回复</span>&nbsp;
                {{ post.details|safe }}
            </div>
            <hr class="span10"/>
            	{% endfor %}
            {% else %}
            	<span>赶快抢沙发吧！！</span>
                <hr class="span10" />
            {% endif %}
        </div>
                      
        <div class='span2' >                      
            {% if has_previous %}
            	<a href="/?page={{ previous }}">上一页</a>
            {% endif %}
            
            {% if has_next %}
            	<a href="/?page={{ next }}"></a>
            {% endif %}
            
            {% if posts_list.has_previous %}
            	<a href="?page={{ posts_list.previous_page_number }}" title="下一页">上一页</a>&nbsp;
            {% endif %}
            
            {% for p in page_range %}
            	{% ifequal p posts_list.number %}
            		<span>第{{ p }}页   </span>
            	{% else %}
            		<a href="?page={{ p }}" title="第{{ p }}页">{{ p }}</a>
            	{% endifequal %}
            {% endfor %}
            
            &nbsp;
            
            {% if posts_list.has_next %}
            	<a href="?page={{ posts_list.next_page_number }}" title="下一页">下一页</a>&nbsp;
            {% endif %}
        </div>
        <hr class="span11" />

        <div class="span11">
            <form name="form1" action="/bbs/subpost/{{ nameid.id }}/" method="POST">
            
            {% if request.session.username %}
                <div class="">    
                    <label for="id_username">作者
                    {{ request.session.username }}&nbsp;&nbsp;
                    <a href="/bbs/logout/" >登出</a>&nbsp;&nbsp;
                    <span ><a href='/'>返回首页</a></span>
                    </label>
                </div>            	
            		
            		
            {% else %}
            	<a href="/" >请先登录</a><br />
            {% endif %}	
                <div class="">    
                    <label for="id_comments">回复内容：</label>
                    {{ form.comments }}
                </div>
                <input class="btn btn-success" type="submit" value="提交" />            	

            </form>
            <script language=“javascript”> document.form1.submit（） </script>
        </div>        
        
    </div>

</div>        



</body>
</html>

templates/success_reg.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>注册成功</title>
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.css">	
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap-responsive.min.css">	
	
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>  
</head>
<body>

<div class='span12'>
    <p align='center'><b>my bbs</b></p><hr />
</div>

<div class="span12">
    
    <div class="span11">
    <span class="label label-success">注册成功 </span>
    </div> 
    <hr class="span11"/>  
    <span class='span10'>   
    您已经注册成功，请您<a href='/'>返回首页</a>登录</span>
    </span>

</div>


</body>
</html>